import React, { useState } from 'react';
import { X, Copy, Check, Printer, Download, Share2 } from 'lucide-react';
import type { AuditResult } from '../types/audit.js';

interface ExportShareModalProps {
  auditResult: AuditResult;
  isOpen: boolean;
  onClose: () => void;
}

export const ExportShareModal: React.FC<ExportShareModalProps> = ({
  auditResult,
  isOpen,
  onClose,
}) => {
  const [copiedMd, setCopiedMd] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = (): string => {
    const { website, scores, summary, highPriorityIssues, strengths, redesignOpportunities } =
      auditResult;

    return `# AI Website Audit Report: ${website.domain}
Scanned: ${new Date(website.scannedAt).toUTCString()}
URL: ${website.finalUrl}

---

## Executive Summary
${summary}

## Scores Overview
- **Overall Score**: ${scores.overall} / 100
- **UX & UI**: ${scores.ux} / 100
- **Technical SEO**: ${scores.seo} / 100
- **Performance**: ${scores.performance} / 100
- **Accessibility**: ${scores.accessibility} / 100
- **Conversion CRO**: ${scores.conversion} / 100

---

## Top High-Priority Issues
${highPriorityIssues
  .map(
    (issue, i) => `### ${i + 1}. ${issue.title} [${issue.severity.toUpperCase()} Priority - ${issue.category.toUpperCase()}]
- **Problem**: ${issue.problem}
- **Evidence**: ${issue.evidence}
- **Impact**: ${issue.impact}
- **Recommendation**: ${issue.recommendation}
`
  )
  .join('\n')}

---

## Strengths
${strengths
  .map(
    (s) => `### ✓ ${s.title} (${s.category.toUpperCase()})
${s.description}
*Evidence: ${s.evidence}*
`
  )
  .join('\n')}

---

## Redesign & Transformation Opportunities
${redesignOpportunities
  .map(
    (opp, i) => `### 0${i + 1}. ${opp.area} [${opp.expectedImpact}]
- **Current Observation**: ${opp.currentObservation}
- **Recommended Redesign**: ${opp.recommendedRedesign}
`
  )
  .join('\n')}

---
*Report generated by AuditorAI (Google AI Studio)*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopiedMd(true);
    setTimeout(() => setCopiedMd(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(auditResult, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `audit-${auditResult.website.domain}-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const markdownText = generateMarkdown();

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fade-in print:hidden">
      <div className="bg-[#0A0A0A] border border-zinc-800 rounded-2xl w-full max-w-3xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="p-6 border-b border-zinc-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-orange-500/10 border border-orange-500/20 flex items-center justify-center text-orange-400">
              <Share2 className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-xs uppercase tracking-[0.3em] font-bold text-zinc-400">
                Export & Share Audit
              </h3>
              <p className="text-xs text-zinc-500 font-mono">
                Deliverable report for stakeholders and web teams
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 text-zinc-400 hover:text-zinc-200 rounded-lg hover:bg-zinc-900 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Action Row */}
        <div className="p-4 border-b border-zinc-800 flex flex-wrap items-center gap-3 bg-zinc-950">
          <button
            onClick={handleCopyMarkdown}
            className="flex items-center gap-1.5 px-4 py-2 text-xs font-semibold text-black bg-white hover:bg-zinc-200 rounded-lg shadow-xs transition-all cursor-pointer"
          >
            {copiedMd ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            <span>{copiedMd ? 'Copied Markdown!' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-4 py-2 text-xs font-semibold text-zinc-300 bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 rounded-lg transition-all cursor-pointer"
          >
            <Printer className="w-4 h-4 text-zinc-400" />
            <span>Print / PDF</span>
          </button>

          <button
            onClick={handleDownloadJson}
            className="flex items-center gap-1.5 px-4 py-2 text-xs font-semibold text-zinc-300 bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 rounded-lg transition-all cursor-pointer"
          >
            <Download className="w-4 h-4 text-zinc-400" />
            <span>Download JSON</span>
          </button>
        </div>

        {/* Markdown Preview */}
        <div className="p-6 overflow-y-auto flex-1 bg-[#050505] font-mono text-xs text-zinc-300 whitespace-pre-wrap leading-relaxed border-t border-b border-zinc-900">
          {markdownText}
        </div>

        {/* Footer */}
        <div className="p-4 bg-zinc-950 border-t border-zinc-800 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold rounded-lg bg-zinc-800 text-zinc-200 hover:bg-zinc-700 cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
